# Site settings
title: Hypothesis
email: hello@hypothesis.works
description: "Find more bugs faster"
logo_location: "https://placeholdit.imgix.net/~text?txtsize=30&bg=F8F8F8&txtclr=002E62&txt=LOGO&w=100&h=100"

#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
  input: GFM

permalink: /:title/

highlighter: rouge

#Other Global Configuration
exclude: ['README.md']

excerpt_separator: <!--more-->

#show the jumbotron header on index page
show_blog_header: true
